### ISSUE TITLE
Android APK Agent 404

### ISSUE THREAD

**Issue by Extarys** [Ylianst/MeshCentralSite#1]
On the page https://meshcentral.com/downloads.html the link for Android APK agent return error 404.

The 404 URI in question is:
```
https://info.meshcentral.com/downloads/MeshCentral2/meshcentral-agent.apk
```

Where can I get the APK in the meantime?
(BTW installed MC for the first time at home today and I'm trying it now, very excited!)
Thanks!

**Comment by si458** [comment]
sadly the old website got shutdown, so @Ylianst had to rebuild it on github
the is some assets missing and links not working,
i dont see `meshcentral-agent.apk` anywhere in the repo, do you have a copy anywhere at all?
and we can reupload/update links?

**Comment by si458** [comment]
the wayback machine has a cached copy for the time being!
https://web.archive.org/web/20220629112338/https://info.meshcentral.com/downloads/MeshCentral2/meshcentral-agent.apk
